esphome:
  name: sbms120
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sbms120 Fallback Hotspot"
    password: "xxxxxxxxxxxx"

captive_portal:
electrodacus_sbms:
  update_interval: 20s

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

sensor:
  - platform: electrodacus_sbms
    voltage:
      name: "Battery Voltage"